config/routes.rb
Rails.application.routes.draw do

  root to: 'app/dashboards#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  namespace :app do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    get 'setting' => 'settings#index',  as: :settings
    get 'report' => 'reports#index',  as: :reports
    get 'assessment' => 'assessments#index',  as: :assessments
    resources :residents
    resources :mobility_assessments
    resources :pain_assessments
    resources :post_fall_assessments

    resources :users do
      collection do
        get :profile
      end
    end
  end

  namespace :admin do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    get 'setting' => 'settings#index',  as: :settings
    get 'report' => 'reports#index',  as: :reports
    resources :users
    resources :businesses, only: [:update] do
      collection do
        get :profile
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  belongs_to :author, class_name: 'User', foreign_key: 'author_id', optional: true
end

app/models/business.rb
# == Schema Information
#
# Table name: businesses
#
#  id            :bigint(8)        not null, primary key
#  business_name :string
#  first_name    :string
#  last_name     :string
#  phone         :string
#  email         :string
#  address       :string
#  city          :string
#  state         :string
#  country       :string
#  author_id     :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  time_zone     :string
#

class Business < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :residents, dependent: :destroy
  has_many :mobility_assessments, dependent: :destroy
  has_many :pain_assessments, dependent: :destroy
  has_many :post_fall_assessments, dependent: :destroy

end

app/models/mobility_assessment.rb
# == Schema Information
#
# Table name: mobility_assessments
#
#  id          :bigint(8)        not null, primary key
#  date        :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  business_id :integer
#  author_id   :integer
#

class MobilityAssessment < ApplicationRecord
  belongs_to :resident, optional: true
end

app/models/pain_assessment.rb
class PainAssessment < ApplicationRecord
  belongs_to :resident, optional: true
end

app/models/post_fall_assessment.rb
class PostFallAssessment < ApplicationRecord
  belongs_to :resident, optional: true
end

app/models/resident.rb
# == Schema Information
#
# Table name: residents
#
#  id                      :bigint(8)        not null, primary key
#  first_name              :string
#  last_name               :string
#  date_of_birth           :date
#  room                    :string
#  author_id               :integer
#  business_id             :integer
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  diagnosis_summary       :string
#  admission_date          :date
#  permanent_resident_date :date
#  status                  :string
#

class Resident < ApplicationRecord
  belongs_to :business, optional: true
  has_many :post_fall_assessments, dependent: :destroy
  has_many :mobility_assessments, dependent: :destroy
  has_many :pain_assessments, dependent: :destroy

  def full_name
  [first_name, last_name].select(&:present?).join(' ').titleize
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#  role                   :string
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string
#  invited_by_id          :integer
#  invitations_count      :integer          default(0)
#  avatar_file_name       :string
#  avatar_content_type    :string
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  business_id            :integer
#  author_id              :integer
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ROLES = [
    ROLE_ADMIN = "Admin",
    ROLE_REGULAR = "Regular"
]

devise :invitable, :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable


validates :first_name, presence: true, length: { maximum: 50 }
validates :last_name, presence: true, length: { maximum: 50 }
validates :role, inclusion: ROLES, presence: true

has_attached_file :avatar, styles: { medium: "450x450>" },
                          default_url: -> (attachment) {
                            ActionController::Base.helpers.asset_path(
                              'default-avatar.png'
                            )
                          }
validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

before_validation :set_role

belongs_to :business, optional: true

def full_name
  [first_name, last_name].join(" ")
end

def admin?
  self.role == ROLE_ADMIN
end

private
def set_role
  self.role = ROLE_ADMIN if self.role.blank?
end
end

app/controllers/app/base_controller.rb
module App
  class BaseController < ApplicationController
    layout 'admin'
    before_action :authenticate_user!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_business
    @current_business ||= current_user.try(:business)
  end

  protected
    def after_sign_in_path_for(resource)
      request.env['omniauth.origin'] || stored_location_for(resource) || app_dashboards_path
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  layout 'visitors'
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/mobility_assessments_helper.rb
module MobilityAssessmentsHelper
end

app/helpers/pain_assessments_helper.rb
module PainAssessmentsHelper
end

app/helpers/post_fall_assessments_helper.rb
module PostFallAssessmentsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/admin/_header.html.erb
<header class="main-header">
    <!-- Logo -->
    <a href="<%= app_dashboards_path %>" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">AH</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">Allied Health</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <a href="<%= app_dashboards_path %>" class="logo mobile">
        <span class="logo-mini">AH</span>
        <span class="logo-lg">Allied Health</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span>
                <img class="user-image" src="<%= current_user.avatar %>" alt="">
                <span class="userName">
                  <%= current_user.first_name %> <%= current_user.last_name %>
                </span>
              </span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-header">
                <p>
                  <%= current_user.email %>
                </p>
              </li>
              <li class="user-footer">
                <div class="pull-left">
                  <a class="btn btn-default btn-flat" href="<%= profile_app_users_path %>">Profile</a>
                </div>
                <div class="pull-right">
                  <a data-method="DELETE" href="<%= destroy_user_session_path %>" href="#" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

app/views/layouts/admin/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
        <div class="pull-left image">
          <img src="<%= current_user.avatar %>" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><%= current_user.first_name %> <%= current_user.last_name %></p>
          <a href="#"> <%= current_user.email %></a>
        </div>
      </div>
      <br>
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
      <li>
        <a href="<%= app_dashboards_path %>">
          <i class="fa fa-dashboard"></i> <span> Dashboard</span>
        </a>
      </li>
      <li>
        <a href="<%= app_residents_path %>">
          <i class="fa fa-user-o"></i> <span> Residents</span>
        </a>
      </li>
      <li>
        <a href="<%= app_assessments_path %>">
          <i class="fa fa-file-o"></i> <span> Assessments</span>
        </a>
      </li>
      <li>
        <a href="<%= app_reports_path %>">
          <i class="fa fa-folder-o"></i> <span> Reports</span>
        </a>
      </li>
      <li>
        <a href="<%= app_settings_path %>">
          <i class="fa fa-cogs"></i> <span> Settings</span>
        </a>
      </li>
    </ul>

  </section>
</aside>