config/routes.rb
Rails.application.routes.draw do

  root to: 'app/dashboards#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  namespace :app do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    get 'setting' => 'settings#index',  as: :settings
    get 'report' => 'reports#index',  as: :reports
    get 'assessment' => 'assessments#index',  as: :assessments
    resources :residents
    resources :mobility_assessments
    resources :pain_assessments
    resources :post_fall_assessments

    resources :users do
      collection do
        get :profile
      end
    end
  end

  namespace :admin do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    get 'setting' => 'settings#index',  as: :settings
    get 'report' => 'reports#index',  as: :reports
    resources :users
    resources :businesses, only: [:update] do
      collection do
        get :profile
      end
    end
  end
end

app/models/post_fall_assessment.rb
class PostFallAssessment < ApplicationRecord
  belongs_to :resident, optional: true
end

app/controllers/app/post_fall_assessments_controller.rb
class App::PostFallAssessmentsController < ApplicationController
  layout 'admin'
  before_action :set_post_fall_assessment, only: [:show, :edit, :update, :destroy, :contacts, :appointments, :progress_notes, :letters, :diagnosis_paragraphs, :incidents, :care_plans, :activities, :tasks, :attachments, :sonas]

  # GET /post_fall_assessments
  # GET /post_fall_assessments.json
  def index
    @post_fall_assessment = current_business.post_fall_assessments.order(created_at: :desc).paginate(:page => params[:page])
  end

  # GET /post_fall_assessments/1
  # GET /post_fall_assessments/1.json
  def show
  end

  # GET /post_fall_assessments/new
  def new
    @post_fall_assessment = current_business.post_fall_assessments.new
  end

  # GET /post_fall_assessments/1/edit
  def edit
  end

  # POST /post_fall_assessments
  # POST /post_fall_assessments.json
  def create
    @post_fall_assessment = current_business.post_fall_assessments.new(post_fall_assessment_params)
    @post_fall_assessment.author_id = current_user.id

    respond_to do |format|
      if @post_fall_assessment.save
        format.html { redirect_to app_post_fall_assessments_path, notice: 'PostFallAssessment was successfully created.' }
        format.json { render :show, status: :created, location: @post_fall_assessment }
      else
        format.html { render :new }
        format.json { render json: @post_fall_assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_fall_assessments/1
  # PATCH/PUT /post_fall_assessments/1.json
  def update
    @post_fall_assessment.author_id = current_user.id

    respond_to do |format|
      if @post_fall_assessment.update(post_fall_assessment_params)
        format.html { redirect_to app_post_fall_assessments_path, notice: 'PostFallAssessment was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_fall_assessment }
      else
        format.html { render :edit }
        format.json { render json: @post_fall_assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_fall_assessments/1
  # DELETE /post_fall_assessments/1.json
  def destroy
    @post_fall_assessment.destroy
    respond_to do |format|
      format.html { redirect_to app_post_fall_assessments_path, notice: 'PostFallAssessment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_fall_assessment
      @post_fall_assessment = current_business.post_fall_assessments.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_fall_assessment_params
      params.require(:post_fall_assessment).permit(:date, :business_id, :author_id, :resident_id)
    end
end

app/helpers/post_fall_assessments_helper.rb
module PostFallAssessmentsHelper
end

app/views/app/post_fall_assessments/_form.html.erb
<%= simple_form_for([:app, @post_fall_assessment]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :date, label: 'Assessment date' %>
    <%= f.association :resident, label_method: :full_name, prompt: "Choose a resident", collection: @current_business.residents.order(:first_name) %>

    <div class="form-group">
      <label>Author</label>
      <input class="form-control" type="text" placeholder="<%= @current_user.full_name %>" readonly value="<%= @post_fall_assessment.author.try(:full_name) %>">
    </div>
    </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/app/post_fall_assessments/edit.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Editing Post Fall Assessment</h3>
  </div>
  <div class="box-body">
    <%= render 'form', post_fall_assessment: @post_fall_assessment %>
  </div>
</div>

app/views/app/post_fall_assessments/index.html.erb
<section class="content">
  <div class="box">
    <div class="box-header">
    <h3 class="box-title">Post Fall Assessments</h3>
      <div class="box-tools">
        <ul class="pull-right">
          <a href="<%= new_app_post_fall_assessment_path %>" class="btn btn-block btn-default btn-sm">New post fall assessment</a>
        </ul>
      </div>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Date</th>
            <th>Resident</th>
            <th>Author</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @post_fall_assessment.each do |post_fall_assessment| %>
            <tr>
              <td><%= post_fall_assessment.date.strftime("%A %v") %></td>
              <td><%= post_fall_assessment.resident&.full_name %></td>
              <td><%= post_fall_assessment.author.try(:full_name) %></td>
              <td><%= link_to 'Show', app_post_fall_assessment_path(post_fall_assessment) %></td>
              <td><%= link_to 'Edit', edit_app_post_fall_assessment_path(post_fall_assessment) %></td>
              <td><%= link_to 'Destroy', app_post_fall_assessment_path(post_fall_assessment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="text-right">
        <%= will_paginate @post_fall_assessment %>
      </div>
    </div>
  </div>
</section>

app/views/app/post_fall_assessments/new.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">New Post Fall Assessment</h3>
      </div>
      <div class="box-body">
        <%= render 'form', post_fall_assessment: @post_fall_assessment %>
      </div>
    </div>
  </div>
</div>

app/views/app/post_fall_assessments/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Post Fall Assessment</h3>
        <div class="box-tools">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Action
            <span class="fa fa-caret-down"></span></button>
          <ul class="dropdown-menu dropdown-menu-right">
            <li><a href="<%= edit_app_post_fall_assessment_path(@post_fall_assessment) %>">Edit</a></li>
            <li><a href="<%= app_post_fall_assessment_path(@post_fall_assessment) %>" data-confirm="Are you sure?" data-method="DELETE" >Delete</a></li>
          </ul>
        </div>
      </div>
      <div class="box-body">
        <p>
          <strong>Date:</strong>
          <%= @post_fall_assessment.date.strftime("%A %v") %>
        </p>


        <p>
          <strong>Resident:</strong>
          <%= @post_fall_assessment.resident&.full_name %>
        </p>

        <p>
          <strong>Author:</strong>
          <%= @post_fall_assessment.author.try(:full_name) %>
        </p>


        </div>
      </div>
    </div>
  </div>